### ISSUE TITLE
Reject links that are not well formed upon checking

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/linkchecker#27]
Links that are not well formed can get stored in the database. When it comes to checking a link and it turns out to be not well formed, give it a status and do not check the actual link.

See https://github.com/clarin-eric/clarin-curation-module/issues/90

**Comment by wowasa** [comment]
I'm shifting this issue towards the rasa mysql implementation since the new host field in the url table since we use, conform to the approach in storm crawler, the the Java method URL.getHost() to fill the field. This throws a MalformedURLException already when the url-string we use to create the URL object is not well formed.  
rasa adds the link to the database with a null-value in the host field and a status record. We must just make sure that only urls were the host field not null are used for link checking, since the status of a non-valid url won't change.
